import Vue from 'vue'
import { Button, Form, FormItem, Input, Link, Col, Row, Message, Container, Aside, Header, Main, Footer, Dropdown, DropdownMenu, DropdownItem, Menu, MenuItem, Submenu, PageHeader, Table, TableColumn, Tag, Popover, Breadcrumb, BreadcrumbItem, Switch, Select, Carousel, CarouselItem, Divider, Tabs, TabPane, Card, Tooltip, Pagination, Dialog, MessageBox, Option, Image, Upload } from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Select)
Vue.use(Input)
Vue.use(Link)
Vue.use(Col)
Vue.use(Row)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(PageHeader)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tag)
Vue.use(Popover)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Switch)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Divider)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Card)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Option)
Vue.use(Image)
Vue.use(Upload)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
